#!/bin/bash
# theme-apply.sh — Apply the active theme from themes.toml to all apps.
#
# Called automatically by DWM on config reload (SIGUSR1 / file save).
# Can also be run manually: theme-apply.sh
#
# Updates: alacritty · kitty · ghostty · rofi · polybar

set -euo pipefail

# ── Locate themes.toml ────────────────────────────────────────────────────────
THEMES_FILE="$HOME/.config/dwm-sky/themes.toml"
if [[ ! -f "$THEMES_FILE" ]]; then
    echo "theme-apply: themes.toml not found at $THEMES_FILE" >&2
    exit 1
fi

# ── Minimal TOML section reader ───────────────────────────────────────────────
# toml_get SECTION KEY FILE — prints the value or empty string
toml_get() {
    local section="$1" key="$2" file="$3"
    awk -v sec="[$section]" -v key="$key" '
        /^\[/ { in_sec = ($0 == sec) }
        in_sec && $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
            sub(/^[^=]*=[[:space:]]*/, "")
            gsub(/"/, "")
            gsub(/[[:space:]]+#.*$/, "")  # strip inline comments (not # in hex colors)
            sub(/[[:space:]]+$/, "")
            print; exit
        }
    ' "$file"
}

# ── Read active theme name ────────────────────────────────────────────────────
THEME_NAME="$(toml_get "active" "theme" "$THEMES_FILE")"
if [[ -z "$THEME_NAME" ]]; then
    echo "theme-apply: no [active] theme set in $THEMES_FILE" >&2
    exit 1
fi

SECTION="theme.$THEME_NAME"

# ── Helper: read a value from the active theme section ───────────────────────
theme_get() {
    toml_get "$SECTION" "$1" "$THEMES_FILE"
}

# ── Read all theme values ─────────────────────────────────────────────────────
TERM_BG="$(theme_get term_bg)"
TERM_FG="$(theme_get term_fg)"
TERM_CURSOR="$(theme_get term_cursor)"
TERM_C0="$(theme_get term_color0)"
TERM_C1="$(theme_get term_color1)"
TERM_C2="$(theme_get term_color2)"
TERM_C3="$(theme_get term_color3)"
TERM_C4="$(theme_get term_color4)"
TERM_C5="$(theme_get term_color5)"
TERM_C6="$(theme_get term_color6)"
TERM_C7="$(theme_get term_color7)"
TERM_C8="$(theme_get term_color8)"
TERM_C9="$(theme_get term_color9)"
TERM_C10="$(theme_get term_color10)"
TERM_C11="$(theme_get term_color11)"
TERM_C12="$(theme_get term_color12)"
TERM_C13="$(theme_get term_color13)"
TERM_C14="$(theme_get term_color14)"
TERM_C15="$(theme_get term_color15)"

GHOSTTY_THEME="$(theme_get ghostty_theme)"
ROFI_THEME="$(theme_get rofi_theme)"

PB_BG="$(theme_get polybar_bg)"
PB_FG="$(theme_get polybar_fg)"
PB_BG_ALT="$(theme_get polybar_bg_alt)"
PB_FG_ALT="$(theme_get polybar_fg_alt)"
PB_ACCENT="$(theme_get polybar_accent)"
PB_URGENT="$(theme_get polybar_urgent)"

# ══════════════════════════════════════════════════════════════════════════════
# ALACRITTY — write ~/.config/alacritty/active-theme.toml
# ══════════════════════════════════════════════════════════════════════════════
ALACRITTY_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/alacritty"
if [[ -d "$ALACRITTY_DIR" ]]; then
    cat > "$ALACRITTY_DIR/active-theme.toml" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
# Change the theme in ~/.config/dwm-sky/themes.toml instead.

[colors.primary]
background = '$TERM_BG'
foreground = '$TERM_FG'

[colors.cursor]
text   = '$TERM_BG'
cursor = '$TERM_CURSOR'

[colors.normal]
black   = '$TERM_C0'
red     = '$TERM_C1'
green   = '$TERM_C2'
yellow  = '$TERM_C3'
blue    = '$TERM_C4'
magenta = '$TERM_C5'
cyan    = '$TERM_C6'
white   = '$TERM_C7'

[colors.bright]
black   = '$TERM_C8'
red     = '$TERM_C9'
green   = '$TERM_C10'
yellow  = '$TERM_C11'
blue    = '$TERM_C12'
magenta = '$TERM_C13'
cyan    = '$TERM_C14'
white   = '$TERM_C15'
EOF

    # Ensure alacritty.toml imports active-theme.toml (add if missing)
    if [[ -f "$ALACRITTY_DIR/alacritty.toml" ]]; then
        if ! grep -q "active-theme.toml" "$ALACRITTY_DIR/alacritty.toml"; then
            # Insert active-theme.toml as first import entry
            sed --follow-symlinks -i 's|^\(import = \[\s*\)|\1\n  "~/.config/alacritty/active-theme.toml",|' \
                "$ALACRITTY_DIR/alacritty.toml"
        fi
        # Replace any existing theme import line to point to active-theme.toml
        # (removes old theme-specific imports, keeps keybinds import)
        sed --follow-symlinks -i 's|"~/.config/alacritty/[^k][^"]*\.toml"|"~/.config/alacritty/active-theme.toml"|g' \
            "$ALACRITTY_DIR/alacritty.toml"
    fi
fi


# ══════════════════════════════════════════════════════════════════════════════
# KITTY — write ~/.config/kitty/active-theme.conf
# ══════════════════════════════════════════════════════════════════════════════
KITTY_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
if [[ -d "$KITTY_DIR" ]]; then
    cat > "$KITTY_DIR/active-theme.conf" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
# Change the theme in ~/.config/dwm-sky/themes.toml instead.

background  $TERM_BG
foreground  $TERM_FG
cursor      $TERM_CURSOR

color0  $TERM_C0
color1  $TERM_C1
color2  $TERM_C2
color3  $TERM_C3
color4  $TERM_C4
color5  $TERM_C5
color6  $TERM_C6
color7  $TERM_C7
color8  $TERM_C8
color9  $TERM_C9
color10 $TERM_C10
color11 $TERM_C11
color12 $TERM_C12
color13 $TERM_C13
color14 $TERM_C14
color15 $TERM_C15
EOF

    # Ensure kitty.conf has 'include active-theme.conf' at the top
    if [[ -f "$KITTY_DIR/kitty.conf" ]]; then
        if ! grep -q "include active-theme.conf" "$KITTY_DIR/kitty.conf"; then
            sed -i '1s|^|include active-theme.conf\n|' "$KITTY_DIR/kitty.conf"
        fi
    fi

    # Signal kitty to reload (no restart needed)
    if command -v kitty &>/dev/null; then
        kill -SIGUSR1 "$(pgrep -x kitty)" 2>/dev/null || true
    fi
fi


# ══════════════════════════════════════════════════════════════════════════════
# GHOSTTY — update ~/.config/ghostty/config
# ══════════════════════════════════════════════════════════════════════════════
GHOSTTY_CFG="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty/config"
# Ensure custom themes shipped with dwm-sky are present
GHOSTTY_THEMES_SRC="$HOME/.local/share/dwm-sky/ghostty/themes"
GHOSTTY_THEMES_DST="${XDG_CONFIG_HOME:-$HOME/.config}/ghostty/themes"
if [[ -d "$GHOSTTY_THEMES_SRC" ]]; then
    mkdir -p "$GHOSTTY_THEMES_DST"
    cp -r "$GHOSTTY_THEMES_SRC/"* "$GHOSTTY_THEMES_DST/" 2>/dev/null || true
fi
if [[ -n "$GHOSTTY_THEME" && -f "$GHOSTTY_CFG" ]]; then
    if grep -q "^theme[[:space:]]*=" "$GHOSTTY_CFG"; then
        sed -i "s|^theme[[:space:]]*=.*|theme = $GHOSTTY_THEME|" "$GHOSTTY_CFG"
    else
        echo "theme = $GHOSTTY_THEME" >> "$GHOSTTY_CFG"
    fi
    # Remove any manually set background/foreground so the named theme controls colors
    sed -i '/^background[[:space:]]*=[^=]/d' "$GHOSTTY_CFG"
    sed -i '/^foreground[[:space:]]*=[^=]/d' "$GHOSTTY_CFG"
fi


# ══════════════════════════════════════════════════════════════════════════════
# ROFI — update @theme line in ~/.config/rofi/config.rasi
# ══════════════════════════════════════════════════════════════════════════════
ROFI_CFG="${XDG_CONFIG_HOME:-$HOME/.config}/rofi/config.rasi"
if [[ -n "$ROFI_THEME" && -f "$ROFI_CFG" ]]; then
    if grep -q '@theme' "$ROFI_CFG"; then
        sed --follow-symlinks -i "s|@theme \".*\"|@theme \"themes/$ROFI_THEME.rasi\"|g" "$ROFI_CFG"
    else
        echo "@theme \"themes/$ROFI_THEME.rasi\"" >> "$ROFI_CFG"
    fi
fi


# ══════════════════════════════════════════════════════════════════════════════
# POLYBAR — fully replace ~/.config/polybar/themes/minimal/colors.ini
# ══════════════════════════════════════════════════════════════════════════════
PB_COLORS="${XDG_CONFIG_HOME:-$HOME/.config}/polybar/themes/minimal/colors.ini"
if [[ -n "$PB_BG" ]]; then
    mkdir -p "$(dirname "$PB_COLORS")"
    # Overwrite the entire file — guarantees consistency across all installs.
    cat > "$PB_COLORS" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
# Change the theme in ~/.config/dwm-sky/themes.toml instead.

[colors]
bg               = $PB_BG
fg               = $PB_FG
bg-alt           = $PB_BG_ALT
fg-alt           = $PB_FG_ALT

blue             = $PB_ACCENT
red              = $PB_URGENT

; These values are computed from the theme's terminal palette.
; Polybar modules that reference \${colors.cyan}, \${colors.green} etc. will
; fall back to the accent/urgent colours above if a theme doesn't define them.
cyan             = $PB_ACCENT
green            = $PB_ACCENT
orange           = $PB_URGENT
pink             = $PB_ACCENT
purple           = $PB_ACCENT
yellow           = $PB_ACCENT

black            = $PB_BG
white            = $PB_FG

trans            = #00000000
semi-trans-black = #aa000000
EOF

    # Restart polybar to pick up the new colors
    if command -v polybar &>/dev/null; then
        POLYBAR_LAUNCH="${XDG_CONFIG_HOME:-$HOME/.config}/polybar/launch.sh"
        if [[ -x "$POLYBAR_LAUNCH" ]]; then
            "$POLYBAR_LAUNCH" &
        fi
    fi
fi


# Restart flameshot so its tray icon picks up the new theme
if pgrep -x flameshot &>/dev/null; then
    pkill -x flameshot 2>/dev/null || true
    sleep 0.3
    flameshot &
fi


echo "theme-apply: applied theme '$THEME_NAME'"
